version: '2'

services: 
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    - "443:443"
    volumes: 
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    - "./nginx/web:/var/www/html"